### ISSUE TITLE
[HU05] Como usuario, poder eliminar una foto ya cargada en el canvas

### ISSUE THREAD

**Issue by bytevictor** [bytevictor/memeHub#5]

**Comment by JJ** [comment]
Esto no está relacionado con ninguna historia de usuario. Todos los issues deben ir avanzando una historia de usuario.

**Comment by bytevictor** [comment]
@JJ esto debería ser su propia HU entiendo no?

**Comment by JJ** [comment]
No lo sé, porque no sé con qué épica encaja. Desde luego, es una tarea de cara al usuario, pero ni indica contexto, ni qué pasa en caso de haber resultados negativos, ni quién ha puesto la foto en el canvas.

**Comment by bytevictor** [comment]
Ha dejado de funcionar por los cambios de 52660bf (Se ha cambiado el anterior canvas para usar react-konva )
